name: run shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello First WorkFlow"
      - name: multiline script
        run: |
          node -v
          npm -v
          java --version
      - name: testing the debugging secrets for runners and actions
        run: echo "this logs are detailed logs for this workflow"
      - name: running python from shell and change shell type
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: powershell-commands
        run: Get-Location
        shell: powershell
      - name: windows-bash
        run: pwd 
        shell: bash